name: Test Patches
on:
    workflow_dispatch:
    schedule:
      # Every day at midnight
      - cron: 0 0 * * *

jobs:
    TestPlugins:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 19
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "pnpm"

            - name: Install dependencies
              run: |
                pnpm install --frozen-lockfile
                pnpm add puppeteer

            - name: Build web
              run: pnpm buildWeb --standalone

            - name: Create Report
              run: |
                export PATH="$PWD/node_modules/.bin:$PATH"
                esbuild test/generateReport.ts > dist/report.mjs
                node dist/report.mjs >> $GITHUB_STEP_SUMMARY
              env:
                DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
